### ISSUE TITLE
better reprasentation of json output

### ISSUE THREAD

**Issue by nimo23** [azaslavsky/domJSON#22]
would be nice to have a option which returns only a minimal set of the dom node, such as 

https://github.com/azaslavsky/domJSON

or even better:

For example, JsonML outputs dom to json like this:

```

var jsonMl =    ["table",{"class":"MyTable","style":"background-color:yellow"},
        ["tbody",
            ["tr",
                ["td",{"class":"MyTD","style":"border:1px solid black"},
                "#550758"],
                ["td",{"class":"MyTD","style":"background-color:red"},
                "Example text here"]
            ],
            ["tr", 
                ["td",{"class":"MyTD","style":"border:1px solid black"},
                "#993101"],
                ["td",{"class":"MyTD","style":"background-color:green"},
                "127624015"]
            ],
            ["tr", 
                ["td",{"class":"MyTD","style":"border:1px solid black"},
                "#E33D87"],
                ["td",{"class":"MyTD","style":"background-color:blue"},
                "\u00A0",
                    ["span",{"id":"mySpan","style":
                    "background-color:maroon;color:#fff 
                    !important"},"\u00A9"],
                    "\u00A0"
                ]
            ]
        ]
    ];
```

Your compiler returns the nodes within a group such as "childNodes" and the like, which is noisy.
Please provide a option to turn the dom-node into this what jsonMl makes but with performance in mind:)

**Comment by azaslavsky** [comment]
Hmm, I'd consider it, though to be honest I'd prefer clarity and completeness to saving bytes.  The purpose of this library is to snapshot the DOM exactly as it is at a given moment, rather than to store the information contained in the DOM in a different format.  The JsonML output, as far as I can tell, is missing a some information from the rendered DOM node (ex: scrollTop).

In the [first example in the demo](https://azaslavsky.github.io/domJSON/#makejson), if you add any field (I used "tagName") to the "domProperties" option and set it to "Includes," the output you get is pretty compact (though admittedly still a bit more verbose than JsonML).  I think this is a solid compromise.
